function run_simulation(mesh)
1+1
%UNTITLED4 Summary of this function goes here
%   Detailed explanation goes here
% flagstr
% [inner_k_left, inner_k_right, inner_h_left, inner_h_right] = ...
%    calc_inner_face_project_permeability(mesh.vertex, mesh.face, ...
%                                             mesh.element, flagstruct);
% [inner_k_eq] = find_eqv_perm(inner_k_left, inner_k_right, inner_h_left, ...
%     inner_h_right, mesh.face.inner.area);
% [bound_k_eq, bound_h_left] = calc_bound_face_project_permeability...
%                         (mesh.vertex, mesh.face, mesh.element, flagstruct);
% calc_inner_gvp(mesh.vertex, mesh.face, mesh.element, inner_k_left, ...
%                 inner_k_right,inner_h_left, inner_h_right, flagstruct);
% calc_bound_gvp(vertex, face, element,bound_k_left, bound_k_right, ...
%     bound_h_left,bound_h_right,flagstruct);
end