function [face_trans_cdt] = create_cdt_face_trans_matrix(mesh, weights)
aux_face_adj = [mesh.face.inner.vertices ; mesh.face.bound.vertices];
count_faces = [1:size(aux_face_adj,1)]';
transm = [mesh.pressure_solver_param.inner.t_eq .* ...
          mesh.pressure_solver_param.inner.gv;     ...
          mesh.pressure_solver_param.bound.t_eq .* ...
                        mesh.pressure_solver_param.bound.gv];
face_node_transm = ...
        sparse(repmat(count_faces,3,1),reshape(aux_face_adj,[],1), ...
        reshape(transm,[],1));
face_trans_cdt = face_node_transm * weights;
end